# Generated by Django 5.0.2 on 2024-03-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('COURSE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DEPT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MODULE_ID', models.IntegerField(default='')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('URN', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=255, null=True)),
                ('LName', models.CharField(max_length=255, null=True)),
                ('preference', models.CharField(choices=[('none', 'None'), ('robotics', 'Robotics'), ('AI', 'Artificial Intelligence')], max_length=50, null=True)),
                ('DEPARTMENT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='myapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Convener',
            fields=[
                ('URN', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=255, null=True)),
                ('LName', models.CharField(max_length=255, null=True)),
                ('MODULE', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='myapp.module')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('ASS_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Total_Mark', models.IntegerField(null=True)),
                ('Pass_Mark', models.IntegerField(null=True)),
                ('Weighting', models.IntegerField(null=True)),
                ('MODULE', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='myapp.module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COURSE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('MODULE', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='myapp.module')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('URN', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=255, null=True)),
                ('LName', models.CharField(max_length=255, null=True)),
                ('preference', models.CharField(choices=[('none', 'None'), ('robotics', 'Robotics'), ('AI', 'Artificial Intelligence')], max_length=50, null=True)),
                ('COURSE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.IntegerField(null=True)),
                ('ACADEMIC', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.academic')),
                ('ASSESSMENT', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='myapp.assessment')),
                ('STUDENT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademicModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACADEMIC', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.academic')),
                ('MODULE', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='myapp.module')),
                ('STUDENT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
