# Generated by Django 5.0.2 on 2024-03-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='preference',
            field=models.CharField(choices=[('none', 'none'), ('robotics', 'robotics'), ('AI', 'AI'), ('cyber security', 'cyber security'), ('web development', 'web development'), ('databases', 'databases'), ('software engineering', 'software engineering'), ('electronic engineering', 'electronic engineering'), ('programming', 'programming'), ('circuit design', 'circuit design'), ('game development', 'game development')], max_length=50, null=True),
        ),
    ]
