# Generated by Django 5.0.2 on 2024-03-02 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulecourse',
            name='COURSE',
        ),
        migrations.RemoveField(
            model_name='modulecourse',
            name='MODULE',
        ),
        migrations.RemoveField(
            model_name='studentacademicmodule',
            name='ACADEMIC',
        ),
        migrations.RemoveField(
            model_name='studentacademicmodule',
            name='MODULE',
        ),
        migrations.RemoveField(
            model_name='studentacademicmodule',
            name='STUDENT',
        ),
        migrations.RenameField(
            model_name='academic',
            old_name='DEPARTMENT',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='MODULE',
        ),
        migrations.RemoveField(
            model_name='convener',
            name='MODULE',
        ),
        migrations.RemoveField(
            model_name='student',
            name='COURSE',
        ),
        migrations.AddField(
            model_name='assessment',
            name='modules',
            field=models.ManyToManyField(to='myapp.module'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='students',
            field=models.ManyToManyField(to='myapp.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(to='myapp.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='assessments',
            field=models.ManyToManyField(to='myapp.assessment'),
        ),
        migrations.AddField(
            model_name='module',
            name='conveners',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='myapp.convener'),
        ),
        migrations.AddField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(to='myapp.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='assessments',
            field=models.ManyToManyField(to='myapp.assessment'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='academic',
            name='URN',
            field=models.CharField(default='0000000', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='ASS_ID',
            field=models.CharField(default='0000000', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='convener',
            name='URN',
            field=models.CharField(default='0000000', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='COURSE_ID',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='DEPT_ID',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='MODULE_ID',
            field=models.CharField(default='', help_text='Three letters followed by four integers, e.g., ABC1234', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='URN',
            field=models.CharField(default='0000000', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(null=True)),
                ('academic', models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='myapp.academic')),
                ('assessment', models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.RESTRICT, to='myapp.assessment')),
                ('student', models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='ModuleCourse',
        ),
        migrations.DeleteModel(
            name='StudentAcademicModule',
        ),
    ]
